### ISSUE TITLE
Compilation fails when loading via devtools or from tar.gz

### ISSUE THREAD

**Issue by marioangst** [YupingLu/biclique#1]
Compliation on my machine, running R 3.3.1 on Windows in RStudio fails both for:

`install.packages("path_to_file/biclique_1.0.0.tar.gz", repos = NULL, type="source")`
and
`devtools::install_github("YupingLu/biclique")`

I have included the error as a txt file.

[20170503_compilation_error.txt](https://github.com/YupingLu/biclique/files/973767/20170503_compilation_error.txt)

**Comment by YupingLu** [comment]
Hi, I got the same error with R 3.3.0. To build the package on windows, you need upgrade R to 3.4.0. https://cran.r-project.org/bin/windows/base/.

Besides, you also need to install Rtools and make sure the system PATH is correct. I installed it directly. https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows

If it's not working for you, please let me know.

Thanks.

**Comment by marioangst** [comment]
Hi,

This works. After updating to R 3.4.0 and taking care that the Rtools PATH variable is correct, the package installs correctly.

Thanks a lot!
