### ISSUE TITLE
Include how to cite

### ISSUE THREAD

**Issue by marioangst** [YupingLu/biclique#3]
Include how to cite the package if used in published work (besides the reference to the paper).

**Comment by YupingLu** [comment]
Hi Mario,
We're still working on the paper. You can state the name of our R package and cite the reference paper which is our previous work on maximal biclique enumeration algorithm. <doi:10.1186/1471-2105-15-110> 
Thanks for your interest in our package. If you have any problem in the future, please feel free to contact us :)
