### ISSUE TITLE
bi.clique() crashes RStudio and RGui

### ISSUE THREAD

**Issue by marioangst** [YupingLu/biclique#5]
I have been experimenting with bi.clique() using different bipartite networks. In most cases, the function works fine and fast.

However, I have come across cases where bi.clique() causes RStudio and RGui to crash. The resulting error output in RStudio is included at the bottom (probably not very informative).

I have attached an example edegelist file ([example_el.txt](https://github.com/YupingLu/biclique/files/988005/example_el.txt)) that reliably causes bi.clique() to crash RStudio and RGui on my Windows machine for all threshhold values I tested.

Another edgelist file interestingly causes RStudio to crash depending on the treshhold values. I have attached it as well ([example2.txt](https://github.com/YupingLu/biclique/files/988015/example2.txt)).
For values of rleast below 3 and small values of lleast (eg. 2), bi.clique("example2.txt") crashes. However, most other values compute as can be seen in the sensitivity chart below, mapping the number of bicliques to a range of values of rleast and lleast.
![sensitivity](https://cloud.githubusercontent.com/assets/19803038/25873195/d4948310-350d-11e7-9bc2-a159eca0daee.png)

By the way, thanks for the great work! I hope I can contribute a little bit by being a guinea pig.

RStudio crash windows error output:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	rsession.exe
  Application Version:	1.0.143.0
  Application Timestamp:	58efc68f
  Fault Module Name:	biclique.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	590aef7a
  Exception Code:	c0000005
  Exception Offset:	0000000000002e6a

**Comment by YupingLu** [comment]
Hi Mario,
Thanks for the feedback. I only considered the ASCII character in this version. I guess that's why RStudio crashes. I'll work on it. You are really contributing.

**Comment by marioangst** [comment]
Hi Yuping

That was indeed the problem. I converted to ASCII characters and now it is running flawlessly. Awesome!
